# project:
#   title: "OpenMUSE"
# 
# editor: visual

project:
  type: book

format: 
  html:
    theme:
      light: flatly
      dark: darkly

book:
# the next option enbale the reader-mode. It hides to TOC and the otpion seems the be automatically enabled by default on Chromium
  #reader-mode: true
  repo-actions: issue
  sidebar:
    border: true
    title: Harmonized Finnish National Bibliography
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: facebook
        href: https://www.facebook.com/

  # file with '#' are not used anymore
  # files with '##' are the one that need to be corrected 
  chapters:
  #- OpenMUSE.qmd
  - metadataJSON.qmd 
 

